services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --host localhost --port 27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  server:
    image: mern-server
    restart: always
    ports:
      - "3001:3001"
    # depends_on:
    #   mongo:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      
  client:
    image: mern-client
    restart: always
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5