services:

  mongo:
    image: mongodb/mongodb-community-server:latest
    restart: always
    env_file:
      - mongo/.env
    volumes:
      - type: bind
        source: mongo/data
        target: /data/db
    healthcheck:
      test: echo 'db.runCommand("hello").ok' | mongosh --host localhost --port 27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    user: "999"
  server:
    image: mern-server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  client:
    image: mern-client
    restart: always
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5